bookbrowse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('book_browse.urls')),
    path('library/', include('library.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    
    
 
    
]
""" Порядок URL маршрутов из переменной urlpatterns имеет значение, так как Django читает файл сверху вниз. Следовательно
когда создается запрос на URL-адрес /accounts/signup, 
Django вначале будет искать в django.contrib.auth.urls, и, не найдя такой, перейдет к приложению accounts.urls """

library/urls.py
from django.urls import path
from django.conf.urls import url

from library import views
from library.views import (
    BookListViewAPI,
    BookDetailViewAPI,
    AuthorListViewAPI,
    AuthorDetailViewAPI,
)


urlpatterns = [
    path("", views.index, name="home"),
    path("books/", views.BookListView.as_view(), name="bookss"),
    url(r"^book/(?P<pk>\d+)$",
        views.BookDetailView.as_view(),
        name="book-detail"),
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    url(
        r"^author/(?P<pk>\d+)$",
        views.AuthorDetailView.as_view(),
        name="author-detail"),
    path("mybooks/",
         views.LoanedBooksByUserListView.as_view(),
         name="my-borrowed"),
    path(
        "book/<uuid:pk>/renew/",
        views.renew_book_librarian,
        name="renew-book-librarian"),
    path("arend/", views.ArendView.as_view(), name="arend"),
    path(
        "adminactionauthor/",
        views.AdminActionAuthorView.as_view(),
        name="admin_action_author",
    ),
    path("author/create/", views.AuthorCreate.as_view(), name="author-create"),
    path("author/update/<int:pk>",
         views.AuthorUpdate.as_view(),
         name="author-update"),
    path("author/delete/<int:pk>",
         views.AuthorDelete.as_view(),
         name="author-delete"),
    path(
        "adminactionbook/",
        views.AdminActionBookView.as_view(),
        name="admin_action_book",
    ),
    path("book/create/", views.BookCreate.as_view(), name="book-create"),
    path("book/update/<int:pk>",
         views.BookUpdate.as_view(),
         name="book-update"),
    path("book/delete/<int:pk>",
         views.BookDelete.as_view(),
         name="book-delete"),
    path("api/v1/books/", BookListViewAPI.as_view(), name="book_list_api"),
    path("api/v1/books/<int:pk>",
         BookDetailViewAPI.as_view(),
         name="book_detail_api"),
    path("api/v1/authors/",
         AuthorListViewAPI.as_view(),
         name="author_list_api"),
    path(
        "api/v1/authors/<int:pk>",
        AuthorDetailViewAPI.as_view(),
        name="author_detail_api",
    ),
]

library/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """

    name = models.CharField(
        max_length=200, help_text="Введите жанр книги", verbose_name="Имя"
    )

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """

    title = models.CharField(max_length=200, verbose_name="Имя")
    author = models.ForeignKey(
        "Author",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Автор",
        related_name="+",
    )

    summary = models.TextField(
        max_length=1000,
        help_text="Напишите описание этой книге",
        verbose_name="Описание",
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
    )
    genre = models.ManyToManyField(
        Genre, help_text="Выберите жанр для этой книги", verbose_name="Жанр"
    )

    summary = models.TextField(
        max_length=1000,
        help_text="Enter a brief description of the book",
        verbose_name="Описание",
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
    )
    genre = models.ManyToManyField(
        Genre, help_text="Select a genre for this book", verbose_name="Жанр"
    )

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):

        return ", ".join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = "Genre"

    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"


class BookInstance(models.Model):

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
    )

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular book across whole library",
    )

    book = models.ForeignKey(
        "Book", on_delete=models.SET_NULL, null=True, verbose_name="Книга"
    )
    imprint = models.CharField(max_length=200, verbose_name="Издательство")
    due_back = models.DateField(null=True,
                                blank=True,
                                verbose_name="Срок годности до:")
    borrower = models.ForeignKey(User,
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ("m", "Обслуживающий"),
        ("o", "В кредит"),
        ("a", "В наличии"),
        ("r", "Забронирован"),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Наличие книги",
        verbose_name="Статус",
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Book availability",
        verbose_name="Статус",
    )

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)
        verbose_name = "Копия книги"
        verbose_name_plural = "Копии книг"

    def __str__(self):
        """
        String for representing the Model object
        """
        return "%s (%s)" % (self.id, self.book.title)


class Author(models.Model):
    """
    Model representing an author.
    """

    book = models.ForeignKey(
        "Book",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Книга",
        related_name="+",
    )
    first_name = models.CharField(max_length=100, verbose_name="Имя")
    last_name = models.CharField(max_length=100, verbose_name="Фамилия")
    date_of_birth = models.DateField(
        null=True, blank=True, verbose_name="Дата рождения"
    )
    date_of_death = models.DateField("Дата смерти", null=True, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return "%s, %s" % (self.last_name, self.first_name)

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"
        ordering = ["last_name"]

library/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from library.models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField()

    def clean_due_back(self):
        data = self.cleaned_data["renewal_date"]

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_("Недействительная дата\
                                    - продление в прошлом"))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _(
                    "Недействительная дата - продление в прошлую дату \
                     - продление более чем на 4 недели вперед"
                )
            )

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        fields = ["due_back"]
        labels = {"due_back": _("New renewal date")}
        help_texts = {
            "due_back": _("Enter a date between now and 4 weeks (default 3).")
        }

library/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics
from rest_framework.permissions import AllowAny
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from library.models import Book, Author, BookInstance
from library.forms import RenewBookForm
from library.serializers import BookSerializer, AuthorSerializer


def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Доступные книги (статус = 'a')
    num_instances_available = BookInstance.objects.filter(
                                status__exact="a").count()
    num_authors = Author.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context
    return render(
        request,
        "index.html",
        context={
            "num_books": num_books,
            "num_instances": num_instances,
            "num_instances_available": num_instances_available,
            "num_authors": num_authors,
            "num_visits": num_visits,
        },
    )


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


# Create your views here.
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 5

    def get_context_data(self, **kwargs):
        # В первую очередь получаем базовую реализацию контекста
        context = super(AuthorListView, self).get_context_data(**kwargs)
        context["some_data"] = "This is just some data"
        return context


class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""

    model = BookInstance
    template_name = "library/bookinstance_list_borrowed_user.html"
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(
            borrower=self.request.user).order_by(
            "due_back"
        )


@login_required
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == "POST":

        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():

            book_instance.due_back = form.cleaned_data["renewal_date"]
            book_instance.borrower = request.user
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse("my-borrowed"))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = (datetime.date.today() +
                                 datetime.timedelta(weeks=3))
        form = RenewBookForm(initial={"renewal_date": proposed_renewal_date})

    context = {
        "form": form,
        "book_instance": book_instance,
    }

    return render(request, "library/book_renew_librarian.html", context)


class ArendView(generic.ListView):
    model = BookInstance
    template_name = "library/arend.html"


class AdminActionAuthorView(generic.ListView):
    model = Author
    template_name = "library/admin_action_author.html"


class AuthorCreate(CreateView):
    model = Author
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    initial = {"date_of_death": "00/00/00"}


class AuthorUpdate(UpdateView):
    model = Author
    fields = (
        "__all__"
    )


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy("authors")


class AdminActionBookView(generic.ListView):
    model = Book
    template_name = "library/admin_action_book.html"


class BookCreate(CreateView):
    model = Book
    fields = ["title", "summary", "isbn", "genre"]


class BookUpdate(UpdateView):
    model = Book
    fields = (
        "__all__"
    )


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy("books")


class BookListViewAPI(generics.ListAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    permission_classes = (AllowAny,)


class BookDetailViewAPI(generics.RetrieveAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class AuthorListViewAPI(generics.ListAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    permission_classes = (AllowAny,)


class AuthorDetailViewAPI(generics.RetrieveAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

library/templates/library/admin_action_author.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список авторов</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a> ({{author.last_name}})
        <a href="{% url 'author-update' author.id %}">Обновить Автора</a> ||
        <a href="{% url 'author-delete' author.id %}">Удалить Автора</a>
      </li>
      {% endfor %}
      <a href="{% url 'author-create' %}">Создать Автора</a>

    </ul>

    {% endif %} 
{% endblock %}

library/templates/library/admin_action_book.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг </h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
<<<<<<< HEAD
        <a href="{% url 'book-update' book.id %}">|| Обновить Книгу</a> ||
        <a href="{% url 'book-delete' book.id %}">|| Удалить Книгу</a>
=======
        <a href="{% url 'book-update' book.id %}">|| Обновить Автора</a> ||
        <a href="{% url 'book-delete' book.id %}">|| Удалить Автора</a>
>>>>>>> b07154f3fcca8999a4ce3efc70d5d1edd3bd6b22
      </li>
      {% endfor %}
      <a href="{% url 'book-create' %}">Создать Книгу</a>

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %} 
{% endblock %}

library/templates/library/arend.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг в аренду</h1>

{% if bookinstance_list %}
    {% for b in bookinstance_list%}

    <ul>
        <li>
            <p>{{ b.book.title }}</p>
            <form action="{% url 'renew-book-librarian'  b.id  %}">
                <button>Взять в аренду</button>
            </form>
            
        </li>
    </ul>

   

    <a href="{% url 'renew-book-librarian'  b.id  %}">{{ b.book.title }}</a><p></br>
    {% endfor %}
    <h1>Если хотите взять в аренду кликните</h1>

{% endif %}
  
{% endblock %}

library/templates/library/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Удаление Автора</h1>

<p>Вы уверены что хотите удалить: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да, удалить.">
</form>

{% endblock %}

library/templates/library/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Имя: {{ author.first_name }}
<<<<<<< HEAD
  {% if author.book_set.all%}
      {% for book in author.book_set.all %}
  <p><strong>Книга:</strong> <a href="{% url 'book-detail' author.book.pk %}">{{ book.title }}</a></p>
      {% endfor %}
  {% endif %}
=======
  
>>>>>>> b07154f3fcca8999a4ce3efc70d5d1edd3bd6b22
  <p><strong>Фамилия:</strong> {{ author.last_name }}</p> <!-- author detail link not yet defined -->
  <p><strong>Дата Рождения:</strong> {{ author.date_of_birth }}</p>
  {% if author.date_of_death is none %}
  <p><strong>Дата Смерти:</strong>Жив(а)</p>
  {% else %}
  <p><strong>Дата Смерти:</strong> {{ author.date_of_death }}</p>
  {% endif %}
  <div style="margin-left:20px;margin-top:20px">
<!--   <p><strong>Language:</strong> {{ author.language }}</p>
  <p><strong>Genre:</strong> {% for genre in author.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  -->
<!-- 
   <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in author.authorinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div> -->
{% endblock %} 

library/templates/library/author_form.html
<<<<<<< HEAD

{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Готово">
=======
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
>>>>>>> b07154f3fcca8999a4ce3efc70d5d1edd3bd6b22
  </form>
{% endblock %}

library/templates/library/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список авторов</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a> ({{author.last_name}})
      </li>
      {% endfor %}

    </ul>

    {% endif %} 
{% endblock %}

library/templates/library/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Удаление книги.</h1>

<<<<<<< HEAD
<p>Вы уверены что хотите удалить: {{ book.name }}?</p>
=======
<p>Вы уверены что хотите удалить: {{ author }}?</p>
>>>>>>> b07154f3fcca8999a4ce3efc70d5d1edd3bd6b22

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да, удалить.">
</form>

{% endblock %}

library/templates/library/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Название: {{ book.title }}</h1>

  <p><strong>Автор:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Описание:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  {% if book.language is none %}
    <pass></pass>
  {% else %}
  <p><strong>Язык:</strong> {{ book.language }}</p>
  {% endif %}
  <p><strong>Жанр:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Копии</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">Статус: {{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Cрок годности до:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Издательство :</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

library/templates/library/book_form.html
{% extends "base_generic.html" %}
<<<<<<< HEAD
{% load crispy_forms_tags %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Готово">
=======

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
>>>>>>> b07154f3fcca8999a4ce3efc70d5d1edd3bd6b22
  </form>
{% endblock %}

library/templates/library/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг </h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>В библиотеке нет книг.</p>
    {% endif %} 
{% endblock %}

library/templates/library/book_renew_librarian.html
{% extends "base_generic.html" %}
<<<<<<< HEAD
{% load crispy_forms_tags %}
=======

>>>>>>> b07154f3fcca8999a4ce3efc70d5d1edd3bd6b22
{% block content %}
  <h1>Имя: {{ book_instance.book.title }}</h1>
  <p>Пользователь: {{ user.get_username }}</p>
  <p {% if book_instance.is_overdue %} class="text-danger"{% endif %}>Дата возврата: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
<<<<<<< HEAD
    {{ form|crispy }}
=======
    <table>
    {{ form.as_table }}
    </table>
>>>>>>> b07154f3fcca8999a4ce3efc70d5d1edd3bd6b22
    <input type="submit" value="Готово!">
  </form>
{% endblock %}

library/templates/library/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Позаимствованные книги</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>У вас нет позаимствованных книг</p>
    {% endif %}
{% endblock %}